// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvmtJvh-yWqN4cKZRPUg33i1QsXqzoSKc',
    appId: '1:476994031236:web:2b13aac784f4f087e8bcd1',
    messagingSenderId: '476994031236',
    projectId: 'app-discussion-forum',
    authDomain: 'app-discussion-forum.firebaseapp.com',
    storageBucket: 'app-discussion-forum.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIE6NNFy46a2NDLzKy9RyeLF0KhQ_2bFs',
    appId: '1:476994031236:android:c86cfd4cec317a84e8bcd1',
    messagingSenderId: '476994031236',
    projectId: 'app-discussion-forum',
    storageBucket: 'app-discussion-forum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4O5U23pBuQtEWiQYaQhSA_fSRb6-nKDo',
    appId: '1:476994031236:ios:749a0db66f141845e8bcd1',
    messagingSenderId: '476994031236',
    projectId: 'app-discussion-forum',
    storageBucket: 'app-discussion-forum.appspot.com',
    iosBundleId: 'com.duktardiscussionForum.discussionForum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4O5U23pBuQtEWiQYaQhSA_fSRb6-nKDo',
    appId: '1:476994031236:ios:0b76fdb1f089f3d6e8bcd1',
    messagingSenderId: '476994031236',
    projectId: 'app-discussion-forum',
    storageBucket: 'app-discussion-forum.appspot.com',
    iosBundleId: 'com.duktardiscussionForum.discussionForum.RunnerTests',
  );
}
